CREATE TABLE casbin_rule (
    id SERIAL PRIMARY KEY,
    p_type VARCHAR(255) DEFAULT '',
    v0 VARCHAR(255) DEFAULT '',
    v1 VARCHAR(255) DEFAULT '',
    v2 VARCHAR(255) DEFAULT '',
    v3 VARCHAR(255) DEFAULT '',
    v4 VARCHAR(255) DEFAULT '',
    v5 VARCHAR(255) DEFAULT ''
);
